general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  startup_commands: ['shell-exec zebar']
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
  config_reload_commands: []
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: true

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: true

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'monitor_focus'

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation and keeps them
  # visible in the taskbar.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: 'cloak'
  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true
  # Gap between adjacent windows.
  inner_gap: '4px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '33 px'
    right: '2px'
    bottom: '4px'
    left: '2px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    hide_title_bar:
      enabled: true
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#75ea07'

  # Visual effects to apply to non-focused windows.
  other_windows:
    hide_title_bar:
      enabled: true
    border:
      enabled: false
      color: '#a1a1a1'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: true

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: true

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: '1'
    bind_to_monitor: 0
  - name: '2'
  - name: '3'
  - name: ''
  - name: 'web'
    bind_to_monitor: 1
    keep_alive: false
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'
  - name: ''

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }
      - window_title: { equals: 'Mem Reduct'}
      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys.PowerAccent' }

      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper*' }

  - commands: ['move --workspace 8']
    match:
    - window_process: { equals: 'TSClient' }

  - commands: ['move --workspace web']
    match:
    # Move windows to workspace 5.
    - window_process: { equals: 'brave' }
  - commands: ['move --workspace ']
    match:
    - window_process: { equals: 'Discord' }
  - commands: ['move --workspace ']
    match:
    - window_process: { equals: 'Spotify' }

  - commands: ['set-floating', 'size --width 1440 --height 810']
    match:
    - window_process: { equals: 'FanSpeedSetting' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

  # When enabled, all keybindings are disabled except for lalt+shift+p which
  # returns to default keybindings.
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['lalt+shift+p']

  # Bind command keys
  - name: 'command::Lock(L)|Restart(R)|Shutdown(S)|Logout(E)'
    keybindings:
      - commands: ['shell-exec rundll32.exe user32.dll,LockWorkStation']
        bindings: ['shift+l']
      - commands: ['shell-exec shutdown /l']
        bindings: ['shift+e']
      - commands: ['shell-exec shutdown /r /t 0']
        bindings: ['shift+r']
      - commands: ['shell-exec shutdown /r /s 0']
        bindings: ['shift+s']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name command::Lock(L)|Restart(R)|Shutdown(S)|Logout(E)']
        bindings: ['escape', 'enter']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['lalt+h', 'lalt+left']
  - commands: ['focus --direction right']
    bindings: ['lalt+l', 'lalt+right']
  - commands: ['focus --direction up']
    bindings: ['lalt+k', 'lalt+up']
  - commands: ['focus --direction down']
    bindings: ['lalt+j', 'lalt+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['lalt+shift+h', 'lalt+shift+left']
  - commands: ['move --direction right']
    bindings: ['lalt+shift+l', 'lalt+shift+right']
  - commands: ['move --direction up']
    bindings: ['lalt+shift+k', 'lalt+shift+up']
  - commands: ['move --direction down']
    bindings: ['lalt+shift+j', 'lalt+shift+down']

  # Resize focused window by a percentage or pixel amount.
  #- commands: ['resize --width -2%']
  #  bindings: ['lalt+u']
  #- commands: ['resize --width +2%']
  #  bindings: ['lalt+p']
  #- commands: ['resize --height +2%']
  #  bindings: ['lalt+o']
  #- commands: ['resize --height -2%']
  #  bindings: ['lalt+i']

  # As an lalternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['lalt+r']

  - commands: ['wm-enable-binding-mode --name command::Lock(L)|Restart(R)|Shutdown(S)|Logout(E)']
    bindings: ['lalt+delete']

  # Disables all keybindings until lalt+shift+p is pressed again.
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['lalt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['lalt+v']

  # Change focus from tiling windows -> floating -> fullscreen.
  # - commands: ['wm-cycle-focus']
  #   bindings: ['lalt+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['lalt+shift+space']

  # Change the focused window to be tiling.
  # - commands: ['toggle-tiling']
  #   bindings: ['lalt+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['lalt+f']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['lalt+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['lalt+shift+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['lalt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['lalt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['lalt+shift+w']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  #- commands: ['shell-exec pwsh']
  #  bindings: ['lalt+enter']

  #- commands: ['shell-exec %ProgramFiles%/SystemInformer/SystemInformer.exe']
  #  bindings: ["lalt+'"]

  #- commands: ['shell-exec %ProgramFiles%/Mem Reduct/memreduct.exe']
  #  bindings: ['lalt+;']
    # bindings: ['lalt+OemQuotes']

  # Focus the next/previous workspace defined in `workspaces` config.
  # - commands: ['focus --next-workspace']
  #   bindings: ['lalt+s']
  # - commands: ['focus --prev-workspace']
  #   bindings: ['lalt+a']

  # Focus the workspace that last had focus.
  # - commands: ['focus --recent-workspace']
  #   bindings: ['lalt+d']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['lalt+1']
  - commands: ['focus --workspace 2']
    bindings: ['lalt+2']
  - commands: ['focus --workspace 3']
    bindings: ['lalt+3']
  - commands: ['focus --workspace ']
    bindings: ['lalt+4']
  - commands: ['focus --workspace web']
    bindings: ['lalt+5']
  - commands: ['focus --workspace 6']
    bindings: ['lalt+6']
  - commands: ['focus --workspace 7']
    bindings: ['lalt+7']
  - commands: ['focus --workspace 8']
    bindings: ['lalt+8']
  - commands: ['focus --workspace 9']
    bindings: ['lalt+9']
  - commands: ['focus --workspace ', 'shell-exec C:/Users/Administrator/AppData/Roaming/Spotify/Spotify.exe']
    bindings: ['lalt+0']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['lalt+shift+a']
  - commands: ['move-workspace --direction right']
    bindings: ['lalt+shift+f']
  - commands: ['move-workspace --direction up']
    bindings: ['lalt+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['lalt+shift+s']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['lalt+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['lalt+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['lalt+shift+3']
  - commands: ['move --workspace ', 'focus --workspace ']
    bindings: ['lalt+shift+4']
  - commands: ['move --workspace web', 'focus --workspace web']
    bindings: ['lalt+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['lalt+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['lalt+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['lalt+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['lalt+shift+9']
  - commands: ['move --workspace ', 'focus --workspace ']
    bindings: ['lalt+shift+0']

  # Bind More Keys
  - commands: ['shell-exec pwsh']
    bindings: ['lalt+i']
  - commands: ['shell-exec wsl']
    bindings: ['lalt+shift+i']
  - commands: ['shell-exec explorer']
    bindings: ['lalt+p']
  #- commands: ['shell-exec %userprofile%/.glzr/glazewm/scripts/OpenStartMenu.vbs"']


